# setup.py
from setuptools import setup, find_packages

setup(
    name="blockscout-client",
    version="1.0.0",
    packages=find_packages(),
    install_requires=[
        "httpx>=0.24.0",
        "pydantic>=2.0.0",
        "click>=8.0.0",
        "rich>=13.0.0",
        "pandas>=1.5.0",
        "tabulate>=0.9.0",
        "pyyaml>=6.0",
    ],
    extras_require={
        "polars": ["polars>=0.18.0"],
    },
    entry_points={
        "console_scripts": [
            "blockscout=blockscout_client.cli.main:cli",
        ],
    },
)